## Lage vektorer og matriser

In [1]:
import numpy as np # Vi importer numpy-pakken med aliaset np

In [2]:
# Lager først en liste og en 2D-liste
vektor = [1, 2, 4]
matrise = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Lager to numpy-vektorer
numpy_vektor1 = np.array(vektor)
numpy_vektor2 = np.array([4, 5, 6])

# Lager to numpy-matriser
numpy_matrise1 = np.array(matrise)
numpy_matrise2 = np.array([[2, 3, 4], [3, 4, 5], [4, 5, 6]])

## Operasjoner på matriser

In [3]:
numpy_vektor1 + numpy_vektor2 # Addisjon av to vektorer

array([ 5,  7, 10])

In [4]:
numpy_matrise1 + numpy_matrise2 # Addisjon av to matriser

array([[ 3,  5,  7],
       [ 7,  9, 11],
       [11, 13, 15]])

In [5]:
numpy_matrise1 @ numpy_matrise2 # Matrisemultiplikasjon av to matriser.

array([[ 20,  26,  32],
       [ 47,  62,  77],
       [ 74,  98, 122]])

## Shape og uthenting av elementer

In [6]:
print(numpy_matrise1.shape) # Finner formen (shape) til en matrise.
print(numpy_vektor1.shape) # Finner formen (shape) til en vektor.

(3, 3)
(3,)


In [7]:
# Kan hente ut elementer fra matriser og vektorer.
print(numpy_matrise1[0, 1])
print(numpy_vektor1[1])

2
2


In [8]:
# Vi kan sette elementer i en matrise/vektor til nye verdier:
numpy_matrise1[0, 1] = 17
print(numpy_matrise1)

[[ 1 17  3]
 [ 4  5  6]
 [ 7  8  9]]


## Spesielle matriser og vektorer

In [9]:
# Vi kan lage identitetsmatrien med eye-metoden.
identitetsmatrise = np.eye(7)
print(identitetsmatrise)

[[ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]]


In [10]:
# Vi kan lage null-matrisen med zeros-metoden.
nullmatrisen = np.zeros((5, 5))
print(nullmatrisen)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [11]:
# Vi kan generere 100 punkter mellom -5 og 5 med linspace-metoden.
hundre_punkter = np.linspace(-5, 5, 100) 
print(hundre_punkter)

[-5.         -4.8989899  -4.7979798  -4.6969697  -4.5959596  -4.49494949
 -4.39393939 -4.29292929 -4.19191919 -4.09090909 -3.98989899 -3.88888889
 -3.78787879 -3.68686869 -3.58585859 -3.48484848 -3.38383838 -3.28282828
 -3.18181818 -3.08080808 -2.97979798 -2.87878788 -2.77777778 -2.67676768
 -2.57575758 -2.47474747 -2.37373737 -2.27272727 -2.17171717 -2.07070707
 -1.96969697 -1.86868687 -1.76767677 -1.66666667 -1.56565657 -1.46464646
 -1.36363636 -1.26262626 -1.16161616 -1.06060606 -0.95959596 -0.85858586
 -0.75757576 -0.65656566 -0.55555556 -0.45454545 -0.35353535 -0.25252525
 -0.15151515 -0.05050505  0.05050505  0.15151515  0.25252525  0.35353535
  0.45454545  0.55555556  0.65656566  0.75757576  0.85858586  0.95959596
  1.06060606  1.16161616  1.26262626  1.36363636  1.46464646  1.56565657
  1.66666667  1.76767677  1.86868687  1.96969697  2.07070707  2.17171717
  2.27272727  2.37373737  2.47474747  2.57575758  2.67676768  2.77777778
  2.87878788  2.97979798  3.08080808  3.18181818  3

In [12]:
# Vi kan generere punkter mellom -5 og 5 med "hopp" på 0.1 med arange-metoden.
mange_punkter = np.arange(-5, 5, 0.1)
print(mange_punkter)

[ -5.00000000e+00  -4.90000000e+00  -4.80000000e+00  -4.70000000e+00
  -4.60000000e+00  -4.50000000e+00  -4.40000000e+00  -4.30000000e+00
  -4.20000000e+00  -4.10000000e+00  -4.00000000e+00  -3.90000000e+00
  -3.80000000e+00  -3.70000000e+00  -3.60000000e+00  -3.50000000e+00
  -3.40000000e+00  -3.30000000e+00  -3.20000000e+00  -3.10000000e+00
  -3.00000000e+00  -2.90000000e+00  -2.80000000e+00  -2.70000000e+00
  -2.60000000e+00  -2.50000000e+00  -2.40000000e+00  -2.30000000e+00
  -2.20000000e+00  -2.10000000e+00  -2.00000000e+00  -1.90000000e+00
  -1.80000000e+00  -1.70000000e+00  -1.60000000e+00  -1.50000000e+00
  -1.40000000e+00  -1.30000000e+00  -1.20000000e+00  -1.10000000e+00
  -1.00000000e+00  -9.00000000e-01  -8.00000000e-01  -7.00000000e-01
  -6.00000000e-01  -5.00000000e-01  -4.00000000e-01  -3.00000000e-01
  -2.00000000e-01  -1.00000000e-01  -1.77635684e-14   1.00000000e-01
   2.00000000e-01   3.00000000e-01   4.00000000e-01   5.00000000e-01
   6.00000000e-01   7.00000000e-01

## Løse ligningsett og determinant

In [13]:
# Vi kan løse ligningsettet Ax = b med solve-metoden. 
A = np.array([[1, 2], [3, 4]])
b = np.array([3, 5])
x = np.linalg.solve(A, b)
print(x)

[-1.  2.]


In [14]:
# Vi kan regne ut determinanten til en matrise med det-metoden.
determinant = np.linalg.det(A)
print(determinant)

-2.0


## Transponering og inversen av en matrise

In [15]:
# Vi kan transponere en matrise med å bruke transpose-metoden.
A_transponert = A.transpose()
print(A_transponert)

[[1 3]
 [2 4]]


In [16]:
# Vi kan regne ut inversen til en matrise med å bruke inv-metoden.
invers_til_A = np.linalg.inv(A)
print(invers_til_A)

[[-2.   1. ]
 [ 1.5 -0.5]]
