## Enkel NumPy 1

I dette Jupyter arket skal vi se på NumPy biblioteket og hvordan man kan lage forskjellige vektorer og matriser. 

In [6]:
# Lager to vanlige Python lister
liste1 = [1, 2, 3]
liste2 = [4, 5, 6]

# Printe ut summen av listene
print("Summen av listene: ", liste1 + liste2)

# Printe ut multiplikasjon av tall med liste
print("\nMultiplikasjon med tall: ", 3 * liste1)

Summen av listene:  [1, 2, 3, 4, 5, 6]

Multiplikasjon med tall:  [1, 2, 3, 1, 2, 3, 1, 2, 3]


Konklusjon: Vanlige Python lister fungerer dårlig til lineær algebra. Heldigvis har vi NumPy pakken!

In [7]:
# Vi importerer NumPy med aliaset np
import numpy as np

In [8]:
# Lager to NumPy vektorer
vektor1 = np.array(liste1)
vektor2 = np.array(liste2)

# Printe ut summen av vektorene
print("Summen av vektorene: ", vektor1 + vektor2)

# Printe ut multiplikasjon av tall med vektor
print("\nMultiplikasjon med tall: ", 3 * vektor1)

Summen av vektorene:  [5 7 9]

Multiplikasjon med tall:  [3 6 9]


In [13]:
# Lager en NumPy matrise
matrise = np.array([[1, 2], [3, 4]])

# Punktvis produkt av matriser
print("Punkvis produkt: \n", matrise * matrise)

# Matrisemultiplikasjon av matriser
print("\nMatrisemultiplikasjon: \n", matrise @ matrise)

Punkvis produkt: 
 [[ 1  4]
 [ 9 16]]

Matrisemultiplikasjon: 
 [[ 7 10]
 [15 22]]


Merk at man gjør matrisemultiplikasjon med @-symbolet. Dette er IKKE det samme som punktvis produkt, som bruker *-symbolet.

## Enkel NumPy 2

Vi skal nå se på hvordan man kan lage spesielle matriser og vektorer, og hvordan man henter ut verdier av matriser og vektorer.

In [17]:
# Lage vektorer med tall på rad
tall_på_rad = np.arange(7, 18, 2)
print(tall_på_rad)

[ 7  9 11 13 15 17]


In [22]:
# Lager matriser med bare nullere
matrise_med_nullere = np.zeros((3, 3))
print("Matrise med bare nullere: \n", matrise_med_nullere)

# Lager matriser med bare enere
matrise_med_enere = np.ones((3, 3))
print("\nMatrise med bare enere: \n", matrise_med_enere)

Matrise med bare nullere: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matrise med bare enere: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Vi kan hente ut elementer fra matriser og vektorer, og deretter sette dem til nye verdier om vi ønsker.

In [23]:
# Hente ut elementer og sette nye verdier
tall_på_rad[1] = 99
print(tall_på_rad)

[ 7 99 11 13 15 17]


In [25]:
# Hente ut en hel rad
rad_med_index_1 = matrise[1, :]

# Hente ut en hel kolonne
kolonne_med_index_1 = matrise[:, 1]

Vi kan sette matriser og vektorer sammen med hstack-kommandoen.

In [49]:
# horisontal stacking
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

np.hstack((vector1, vector2))

array([1, 2, 3, 4, 5, 6])